version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bdd_denuncias_publicas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tesis:/docker-entrypoint-initdb.d

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - media_data:/app/media
    environment:
      DEBUG: "True"
      DB_NAME: bdd_denuncias_publicas
      DB_USER: postgres
      DB_PASSWORD: 2002
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
  media_data: